export type AppContextProps = {
  countOne: number;
  countTwo: number;
  countThree: number;
  countFour: number;
  countFive: number;
  countSix: number;
  countSeven: number;
  countEight: number;
  countNine: number;
  countTen: number;
  priceOne: number;
  priceTwo: number;
  priceThree: number;
  priceFour: number;
  priceFive: number;
  priceSix: number;
  priceSeven: number;
  priceEight: number;
  priceNine: number;
  priceTen: number;
  handleCountOneUp: (price: number) => void;
  handleCountOneDown: (price: number) => void;
  handleCountTwoUp: (price: number) => void;
  handleCountTwoDown: (price: number) => void;
  handleCountThreeUp: (price: number) => void;
  handleCountThreeDown: (price: number) => void;
  handleCountFourUp: (price: number) => void;
  handleCountFourDown: (price: number) => void;
  handleCountFiveUp: (price: number) => void;
  handleCountFiveDown: (price: number) => void;
  handleCountSixUp: (price: number) => void;
  handleCountSixDown: (price: number) => void;
  handleCountSevenUp: (price: number) => void;
  handleCountSevenDown: (price: number) => void;
  handleCountEightUp: (price: number) => void;
  handleCountEightDown: (price: number) => void;
  handleCountNineUp: (price: number) => void;
  handleCountNineDown: (price: number) => void;
  handleCountTenUp: (price: number) => void;
  handleCountTenDown: (price: number) => void;
  handleValueZero: () => void;
};
